(setq my/citar-bibliography '("~/Documents/books/references.bib"))
(setq my/citar-library-paths '("~/Documents/books"))
(setq my/citar-notes-paths '("~/Documents/books/notes"))
(setq my/denote-directory "~/Documents/notes")
(setq my/system-theme 'modus-vivendi)
(setq my/org-directory "~/drive/org/")
