(setq my/citar-bibliography '("~/Documents/books/references.bib"))
(setq my/citar-library-paths '("~/Documents/books"))
(setq my/citar-notes-paths '("~/Documents/books/notes"))
(setq my/denote-directory "~/Documents/notes")
(setq my/system-theme 'modus-vivendi)
(setq my/org-directory "~/org/")
(setq my/browse-url-browser-function 'browse-url-firefox)
(setq my/default-font "Iosevka-10")

(setq my/org-agenda-custom-commands
        '(("i" "Inbox" tags-todo "+inbox")
	      ("s" "Shopping List" tags-todo "+buy")
          ("o" "Todo" tags-todo "-project-someday-@aabacka/!-WAITING"
           ((org-agenda-skip-function '(org-agenda-skip-subtree-if 'scheduled))
            (org-agenda-skip-function '(org-agenda-skip-subtree-if 'deadline))
            (org-agenda-skip-function '(org-agenda-skip-subtree-if 'timestamp))))
          ("w" "Waiting" tags "/WAITING")
          ("S" "Someday" tags-todo "+someday")))

(setq my/org-capture-templates
        '(("i" "Inbox" entry (file+headline "notes.org" "Inbox")
           "* %?\n%U")
          ("t" "Task" entry (file+headline "notes.org" "Tasks")
           "* TODO %?\n%U")
          ("m" "Mail" entry (file+headline "notes.org" "Inbox")
           "* %:fromname\n%U\n%a\n%?")
          ("j" "Journal" entry (file+olp+datetree "notes.org" "Journal")
           "* %U %^{Title}\n%U\n%?")
          ("J" "Journal (custom datetime)" entry (file+olp+datetree "notes.org" "Journal")
           (file "~/Templates/journal.org") :time-prompt t)
          ("p" "Protocol" entry (file+headline "notes.org" "Inbox")
           "* %^{Title}\n%U\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
	      ("L" "Protocol Link" entry (file+headline "notes.org" "Inbox")
           "* %?[[%:link][%:description]] \n%U")))
